pipeline {
  environment {
    registry = "crycrime/devops_adv"
    registryCredential = 'dockerhub_credentials'
    dockerImage = ''
  }

  agent any

  stages {
    stage('Checkout code') {
        steps {
            checkout scm
        }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build ("dev:ops", "-f /devops_adv/les_03/ .")
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}
